name: Publish Astro Build

on:
  push:

jobs:
  publish-html:
    runs-on: ["blog"]
    # defaults:
    #   run:
    #     shell: bash
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.4.0
          registry-url: https://npm.pkg.github.com/
      - uses: actions/checkout@v4
