name: Publish Astro Build

on:
  push:
    branches:
      - main

env:
  OUT: /html-blog

jobs:
  publish-html:
    runs-on: ["blog"]
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        shell: bash
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.4.0
          # registry-url: https://npm.pkg.github.com/
          cache: "yarn"

      - name: Set up package
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile # optional, --immutable

      - name: Build blog
        if: ${{ github.ref == 'ref/head/main' }}
        run: |
          yarn run build

      - name: Clean HTML dir
        if: ${{ github.ref == 'ref/head/main' }}
        continue-on-error: true
        run: |
          find "${OUT}/" -name . -o -prune -exec rm -rf -- {} +

      - name: Copy build to HTML dir
        if: ${{ github.ref == 'ref/head/main' }}
        run: |
          cp -r "${{ github.workspace }}"/dist/* "${OUT}/"
